### ISSUE TITLE
migrations implementation

### ISSUE THREAD

**Issue by sdarwin** [sanoguzhan/django-helm-chart#3]
I'm investigating what the possibilities are to run database migrations.  You are using initContainers.  The problem with initContainers is they are associated with a pod. Let's say the deployment is scaled to 3 pods. The database migrations will run 3 times, right?

A better solution is to include one "job" in the helm chart and have helm hooks run the job during each app upgrade. 

Are there yet other solutions besides those? that is the question.

**Comment by sanoguzhan** [comment]
Sorry for the late response. It seems I missed the notification for this issue. Regarding your point about using initContainers, you're absolutely right. Init containers run before each pod, ensuring that the migrations are applied or skipped for each pod individually. This is the reason why I chose to use initContainers - I wanted to ensure that the migrations run successfully before creating any new pods during a new version deployment. Even if a migration fails, it won't affect the deployment, and the application can still remain in a consistent state.

On the other hand, with a Job, the migration process is decoupled from the pod creation process. If a migration Job fails, it won't block the deployment or prevent the creation of new pods. This decoupling can be advantageous if you prefer to handle the migration process separately from the deployment process and have the flexibility to manage failures independently.

Thank you for pointing that out.

**Comment by sdarwin** [comment]
The issue I was worried about, is that using initContainers creates a race condition.

Let's say the cluster scales out to 10 pods. 

They all launch at the same time, and run their  init containers.

10 database migrations are active at literally the same time. This might create duplicate entries in the database somehow.

**Comment by eljeffeg** [comment]
This doesn't resolve the issue above, but here is something I did as MySQL wasn't ready when the init ran.  I also had to put numbers in front of them as they were not running in order otherwise (I had additional inits).
```yaml
init:
  1_dependency:
    enabled: true 
    name: dependency
    # Creates a delay to wait for MySQL to become available before running migrations
    command: 'echo "Waiting for MySQL Connection..."; while ! nc -z releasename-mysql 3306 2>/dev/null; do sleep 1; done; echo "* MySQL is Online *"'
  2_migrations:
    enabled: true
    name: migrations
    command:  "python3 manage.py migrate"
  3_staticfiles:
    enabled: true
    name: staticfiles
    command: "python3 manage.py collectstatic --noinput;'
 ```
